#!/bin/sh

if [ -z "$1"         ] ; then
  exit
fi

if [ $1 = "-zero"    ] ; then echo -n "\e[0m"    ; fi

if [ $1 = "-black"   ] ; then echo -n "\e[0;30m" ; fi
if [ $1 = "-gray"    ] ; then echo -n "\e[1;30m" ; fi
if [ $1 = "-red"     ] ; then echo -n "\e[0;31m" ; fi
if [ $1 = "-lred"    ] ; then echo -n "\e[1;31m" ; fi
if [ $1 = "-green"   ] ; then echo -n "\e[0;32m" ; fi
if [ $1 = "-lgreen"  ] ; then echo -n "\e[1;32m" ; fi
if [ $1 = "-yellow"  ] ; then echo -n "\e[0;33m" ; fi
if [ $1 = "-lyellow" ] ; then echo -n "\e[1;33m" ; fi
if [ $1 = "-blue"    ] ; then echo -n "\e[0;34m" ; fi
if [ $1 = "-lblue"   ] ; then echo -n "\e[1;34m" ; fi
if [ $1 = "-purple"  ] ; then echo -n "\e[0;35m" ; fi
if [ $1 = "-lpurple" ] ; then echo -n "\e[1;35m" ; fi
if [ $1 = "-cyan"    ] ; then echo -n "\e[0;36m" ; fi
if [ $1 = "-lcyan"   ] ; then echo -n "\e[1;36m" ; fi
if [ $1 = "-lgray"   ] ; then echo -n "\e[0;37m" ; fi
if [ $1 = "-white"   ] ; then echo -n "\e[1;37m" ; fi

shift

echo -n $*
