#!/usr/local/bin/perl
# sift -	Sift through a host-selective meta-file
#
# $Id: sift,v 1.3 1996/03/18 23:10:31 wwcoot Exp $
# $Source: /src/usr/local/bin/sift/sift,v $
#
# SYNOPSIS
#	sift <hostname> <source.sift> > <sifted-file>
#
# DESCRIPTION
#	The input to sift is a meta-file, containing selection
#	directives, which choose whether or not to output specific
#	text based on whether the target host should see the text.
#
#	The output of sift is (ideally) a configuration file that has
#	been tailored to suit a specific host, depending on that
#	host's architecture, or it's specific purpose.
#

$Program = "sift";
$Usage = "usage: $Program hostname source.sift > sifted-file";

#
# This contains site-specific sift directives
#
$SITE_SIFT = "/usr/local/lib/site.sift";

if ($#ARGV != 1) {
    print (STDERR $Usage, "\n");
    exit (1);
}

$Defined{'*'} = 1;

($Host, $Source) = @ARGV;

$Defined{$Host} = 1;

if (-r $SITE_SIFT) {
    &sift ($SITE_SIFT);
}

&sift ($Source);

exit (0);


##############################################################################
# sift -	Sift the named file
#
sub sift {
    local ($source) = shift (@_);

    local ($output) = 1;
    local ($selector) = '*';
    local ($value) = 1;

    if (! open (SOURCE, '<' . $source)) {
	die "$Program: $source: $!\n";
    }

    while (<SOURCE>) {
	if (/^\(([^)]*)\)/) {
	    $directive = $1;
	    @tokens = split (/\s+/, $directive);

	    if ($#tokens > 1) {
		if ($tokens[1] eq '=') {
		    #
		    # Name assignment
		    #
		    $new_name = shift (@tokens);
		    shift (@tokens);
		    if (&evaluate (@tokens)) {
			$Defined{$new_name} = 1;
		    }
		    next;
		}
	    }
	    $output = &evaluate (@tokens);
	} else {
	    next if (! $output);

	    s/__HOST__/$Host/;
	    print;
	}
    }
    close (SOURCE);
}

##############################################################################
# evaluate -	Is the expression true?
#
sub evaluate {
    local (@tokens) = @_;

    local ($true) = 1;

    if ($tokens[0] eq '!') {
	$true = 0;
	shift (@tokens);
    }

    if (grep ($Defined{$_} == 1, @tokens)) {
	return $true;
    }
    return (! $true);
}
